-- Insertion d'un contrat type 'Ingénierie'
INSERT INTO `devis_app`.`CONTRAT` (`CODE`, `TYPE`) values
('A01', 'Performance énérgétique ou environnementale'),
('A0100', ' Perfomance énérgétique ou environnementale'),
('A02', 'Autres'),
('A0200', 'Autres'),
('B01', 'Ensemblier'),
('B0101', 'Ensemblier'),
('B', 'Ensemblier'),
('C', 'Installation'),
('C00', 'Installation'),
('C0000', 'Installation'),
('D', 'Maintenance et facility management'),
('D01', 'Maintenance'),
('D0100', 'Maintenance'),
('D02', 'Facility Management'),
('D0200', 'Facility Management'),
('E', 'Exploitation'),
('E01', 'Engagement énergétique ou environ.'),
('E0100', 'Engagement énergétique ou environ.'),
('E02', 'Autres'),
('E0200', 'Autres'),
('A', 'Conseil et ingénierie'),
('A01', 'Performance énergétique ou environnementale'),
('A0101', 'Axians conseil métier'),
('A0102', 'Axians conseil technologique'),
('A0103', 'Axians activités sur site'),
('A02', 'Autres'),
('A0201', 'Axians conseil métier'),
('A0202', 'Axians conseil technologique'),
('A0203', 'Axians activité sur site'),
('B', 'Ensemblier'),
('B01', 'Ensemblier'),
('B0101', 'Ensemblier'),
('C03', 'Axians recherche et négociation'),
('C0301', 'Axians recherche et négociation'),
('C04', 'Axians déploiement'),
('C0401', 'Axians déploiement'),
('C05', 'Axians installation & mise en œuvre'),
('C0501', 'Axians installation & mise en œuvre'),
('C06', 'Axians développement'),
('C0601', 'Axians développement'),
('D0101', 'Axians maintenance curative'),
('D0102', 'Axians maintenance préventive'),
('D0103', 'Axians vie du réseau'),
('E0101', 'Axians service IT à la demande'),
('E0102', 'Axians outsourcing'),
('E0103', 'Axians services managés'),
('E0201', 'Axians service IT à la demande'),
('E0202', 'Axians outsourcing'),
('E0203', 'Axians services managés'),
('A0100', 'Perfomance énergétique ou environ.'),
('A0200', 'Autres'),
('B02', 'BS bâtiment neuf'),
('B0201', 'BS bâtiment neuf'),
('B03', 'BS bâtiment existant'),
('B0301', 'BS bâtiment existant'),
('C01', 'BS bâtiment neuf'),
('C0101', 'Client existant'),
('C0102', 'Nouveau client'),
('C02', 'BS bâtiment existant'),
('C0201', 'Tvx neufs - Marché à bon de cde'),
('C0202', 'Tvx neufs - Travaux courants'),
('C0203', 'Tvx neufs - Projet / client existant'),
('C0204', 'Tvx neufs - Projet / nouveau client'),
('C0205', 'Rehab - Marché à bon de commande'),
('C0206', 'Rehab - Travaux courants'),
('C0207', 'Rehab - Client existant'),
('C0208', 'Rehab - Nouveau client'),
('D0104', 'BS forfait'),
('D0105', 'BS hors forfait'),
('D0201', 'BS FM Intégré / forfait'),
('D0202', 'BS FM intégré / hors forfait'),
('D0203', 'BS services aux occup. / forfait'),
('D0204', 'BS services aux occup. / h. forfait');