import { Router } from 'express';
import adminRoutes from './adminRoutes.js';
import clientRoutes from './clientRoutes.js';
import commanditaireRoutes from './commanditaireRoutes.js';
import contratRoutes from './contratRoutes.js';
import detailModalRoutes from './detailModalRoutes.js';
import devisRoutes from './devisRoutes.js';
import domaineRoutes from './domaineRoutes.js';
import expertiseRoutes from './expertiseRoutes.js';
import fraisRoutes from './fraisRoutes.js';
import posteRoutes from './posteRoutes.js';
import achatRoutes from './segmentationRoutes/achatRoutes.js';
import fraisFournitureRoutes from './segmentationRoutes/fraisFournitureRoutes.js';
import sectionRoutes from './segmentationRoutes/sectionRoutes.js';
import userRoutes from './userRoutes.js';
const router = Router();

router.use('/contrats', contratRoutes);
router.use('/expertises', expertiseRoutes);
router.use('/domaines', domaineRoutes);
router.use('/fraisC', fraisRoutes);
router.use('/clients', clientRoutes);
router.use('/commanditaires', commanditaireRoutes);
router.use('/admin', adminRoutes);
router.use('/users', userRoutes);
router.use('/devis', devisRoutes);
router.use('/sections', sectionRoutes);
router.use('/achats', achatRoutes);
router.use('/frais', fraisFournitureRoutes);
router.use('/postes', posteRoutes);
router.use('/postesDetail', detailModalRoutes);
export default router;
